"""Small interfaces shared by detection runtime components."""

from typing import Any, Protocol


class InterpreterProtocol(Protocol):
    def allocate_tensors(self) -> None: ...

    def get_input_details(self) -> list[dict[str, Any]]: ...

    def get_output_details(self) -> list[dict[str, Any]]: ...

    def set_tensor(self, tensor_index: int, value: Any) -> None: ...

    def invoke(self) -> None: ...

    def get_tensor(self, tensor_index: int) -> Any: ...
